# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux-x64, linux-arm64, win-x64, osx-x64, osx-arm64]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Remove update commands
      run: |
        sed -i '/new UpdateCommand(),/d' Lapis/Commands/GroupCommands/MaiCommand.cs
        sed -i '/new BindCommand(),/d' Lapis/Commands/GroupCommands/MaiCommand.cs
        sed -i '/new UpdateCommand()/d' Lapis/Commands/GroupCommands/MaiCommand.cs
        sed -i '/new BindCommand()/d' Lapis/Commands/GroupCommands/MaiCommand.cs
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish - ${{ matrix.os }}
      run: |
        dotnet publish \
          -c Release \
          -r ${{ matrix.os }} \
          --self-contained false \
          /p:PublishSingleFile=true \
          /p:PublishTrimmed=false \
          /p:IncludeNativeLibrariesForSelfExtract=true \
          -o publish/${{ matrix.os }}

    - name: Upload Artifact - ${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: publish/${{ matrix.os }}
